### ISSUE TITLE
cant login because Login sceen flickers 

### ISSUE THREAD

**Issue by SpeeterYT** [scubajeff/lespas#53] opened 2022-04-02 09:18 UTC
**Describe the bug**
when trying to log in, the login sceen starts flickering. On every device I tried its the same. F-Droid aswell as PlayStore. Sometimes the background image does the same.

**To Reproduce**
1. Go to the login screen
2. Log in with URL i cant show
3. See error

**Expected behavior**
Being able to type in the login Field

**Screenshots**

https://user-images.githubusercontent.com/80942857/161376535-98e02f14-439f-4bd6-9a24-9393aacfcee1.mov

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9, Windows Subsystem for Android
 - OS: Android 11 MIUI, Android 11
 - Version 2.5.4 F-Droid, GooglePlay

**Additional context**
Is it the BG?

**Comment by scubajeff** [comment] 2022-04-02 11:47
stock xiaomi os?
what is windows subsystem? r u installing on windows subsystem emulator or a xiaomi device?

**Comment by SpeeterYT** [comment] 2022-04-02 13:03
> 

Yes, stock xiaomi os, WSA is a official microsoft tool to run APKs on Windows 11.

**Comment by scubajeff** [comment] 2022-04-02 15:16
so you mean you tested both, and all of them have this issue?

**Comment by scubajeff** [comment] 2022-04-02 15:30
from the screenshot, Les Pas is in the authentication screen, and it's loading pages from your server in a webview, seems like the webview can't hold it's background stable and keep showing some content from beneath it. Is that a distored version of your wallpaper?

**Comment by SpeeterYT** [comment] 2022-04-02 16:03
> from the screenshot, Les Pas is in the authentication screen, and it's loading pages from your server in a webview, seems like the webview can't hold it's background stable and keep showing some content from beneath it. Is that a distored version of your wallpaper?

A cropped version

**Comment by SpeeterYT** [comment] 2022-04-02 16:03
> so you mean you tested both, and all of them have this issue?

Right

**Comment by scubajeff** [comment] 2022-04-02 16:38
seems to me there are conflicts between lespas's animation and your device's hardware graphic acceleration. further debuging requires that you install a test version of lespas. r u ready to help on this?

**Comment by SpeeterYT** [comment] 2022-04-02 20:06
> 

Yes

**Comment by scubajeff** [comment] 2022-04-03 02:57
great. could you leave your address at scubajeffrey@criptext.com?

**Comment by scubajeff** [comment] 2022-04-03 03:06
btw, have you theme your Nextcloud server? is it possible to send the output of the following command to my email mentioned above?
`
curl -X GET 'https://<your_nextcloud_server_url>/v2.php/cloud/capabilities?format=json' -H "OCS-APIRequest: true"
`

**Comment by SpeeterYT** [comment] 2022-04-03 09:38
When I run the command I dont get any output:
https://i.imgur.com/CW9zPxu.png

**Comment by SpeeterYT** [comment] 2022-04-03 09:43
on windows I get this:
https://i.imgur.com/FCGoO3o.png

**Comment by scubajeff** [comment] 2022-04-03 15:38
ok, forget that. please just send me your address so that I can mail you a debug version for testing

**Comment by SpeeterYT** [comment] 2022-04-04 11:51
> ok, forget that. please just send me your address so that I can mail you a debug version for testing

speeterapps@gmx.de

**Comment by SpeeterYT** [comment] 2022-04-05 19:33
I have installed it, what should I do?

**Comment by scubajeff** [comment] 2022-04-06 04:00
see if it fixes the flickering issue

**Comment by SpeeterYT** [comment] 2022-04-06 18:26
> see if it fixes the flickering issue

No, it doesn't

**Comment by scubajeff** [comment] 2022-04-07 03:02
before the login page shown, there is a brief moment when a progress bar showing in the middle of screen, did you manage to see that? is the background flickering during that period of time?

**Comment by SpeeterYT** [comment] 2022-04-09 17:44
https://user-images.githubusercontent.com/80942857/162585464-83035981-06e5-4a02-8807-a8f81f8a5507.mp4

Can you see anything there?

**Comment by scubajeff** [comment] 2022-04-10 01:57
thank you. i can see the slogan from your server flash on screen for a second. that help to narrow down the cause of this issue  to webview implementation

**Comment by SpeeterYT** [comment] 2022-04-10 09:23
> thank you. i can see the slogan from your server flash on screen for a second. that help to narrow down the cause of this issue to webview implementation

can I fix that?

**Comment by scubajeff** [comment] 2022-04-10 10:49
it's totally fine to clone and fix it on your side. it's hard for me to debug this one remotely.

**Comment by Sewdohe** [comment] 2022-04-12 21:31
I'm also having this issue on a fresh install of AOSP ROM using android 12L, tried using both the F-droid and play store package. Could this be an issue regarding not having chrome installed?

**Comment by scubajeff** [comment] 2022-04-12 23:40
@Sewdohe have you tried the debug version i posted in this thread? in that version, i have removed all view animations of the login screen. i'm not sure if it's a chrome issue, i believe android webview is a build-in system service, although you can replace it in a rooted environment.

**Comment by Sewdohe** [comment] 2022-04-13 18:41
@scubajeff Just tried it, having the same issue. I am rooted, however, so I'll try switching my WebView and see if that helps. last I tried though bromite was crashing on 12L

**Comment by Sewdohe** [comment] 2022-04-13 21:19
> @scubajeff Just tried it, having the same issue. I am rooted, however, so I'll try switching my WebView and see if that helps. last I tried though bromite was crashing on 12L

Tried with bromite sys WebView, that exhibited the same flickering issue

**Comment by scubajeff** [comment] 2022-04-15 12:43
@Sewdohe let me get this clearly. 12L AOSP fresh install, both android webview and bromite webview suffered from this bug.

**Comment by Sewdohe** [comment] 2022-04-15 17:09
> @Sewdohe let me get this clearly. 12L AOSP fresh install, both android webview and bromite webview suffered from this bug.

Yes sir, fresh install with no root or modules

then I tried it again after installing magisk and changing the webview to bromite with the same results.

If there is anything I can do to help, let me know. I'm not super familiar with android development, but I am a developer, so I'm sure I could be of some use. Could get a logcat or something

**Comment by scubajeff** [comment] 2022-04-16 04:58
I thought this only affects oem rom like miui, but yours is AOSP. I will try to reproduct it in my environment. Logcat won't do much in this moment, since it's not a crash. Mind telling me what model of your phone is?

**Comment by scubajeff** [comment] 2022-04-16 05:57
Just tested in a 12L android emulator, can't reproduce this issue.

**Comment by Sewdohe** [comment] 2022-04-16 18:42
> I thought this only affects oem rom like miui, but yours is AOSP. I will try to reproduct it in my environment. Logcat won't do much in this moment, since it's not a crash. Mind telling me what model of your phone is?

It's a Pixel 5. Running ProtonAOSP rom, no gapps, sandboxed google play services, rooted, running protonKernel

**Comment by scubajeff** [comment] 2022-04-17 02:10
@Sewdohe , Ok, that's a custom ROM, though it's based on ASOP. On Nextcloud server, you can enable an app called Theming, in that app, you can customized your instance's theme color, backgroud wallpaper and showing a slogan on login page. Have you done those modification? If not, could you try to set a theme color of your choice and test LesPas login again?

**Comment by scubajeff** [comment] 2022-04-17 02:41
By the way, Bromite is also based on Chrome.

**Comment by Sewdohe** [comment] 2022-04-17 04:13
> By the way, Bromite is also based on Chrome.

everything is based on chrome nowadays lmao

**Comment by scubajeff** [comment] 2022-04-17 05:44
@Sewdohe could you please try this debug built?
[LesPas-v2.5.5-debug.zip](https://github.com/scubajeff/lespas/files/8501066/LesPas-v2.5.5-debug.zip)

**Comment by scubajeff** [comment] 2022-04-17 05:54
@Sewdohe could you please try this debug built?
[LesPas-v2.5.5-debug.zip](https://github.com/scubajeff/lespas/files/8501077/LesPas-v2.5.5-debug.zip)

**Comment by Sewdohe** [comment] 2022-04-17 06:40
> @Sewdohe could you please try this debug built? [LesPas-v2.5.5-debug.zip](https://github.com/scubajeff/lespas/files/8501077/LesPas-v2.5.5-debug.zip)

Updated current install with the debug package, still having flickering

**Comment by Sewdohe** [comment] 2022-04-26 01:56
Anything else I can do to help find the issue here? Really wanna try this app

**Comment by scubajeff** [comment] 2022-04-26 02:27
@Sewdohe ,On Nextcloud server, you can enable an app called Theming, in that app, you can customized your instance's theme color, backgroud wallpaper and showing a slogan on login page. Have you done those modification? If not, could you try to set a theme color of your choice and test LesPas login again?

**Comment by Sewdohe** [comment] 2022-04-26 05:13
> @Sewdohe ,On Nextcloud server, you can enable an app called Theming, in that app, you can customized your instance's theme color, backgroud wallpaper and showing a slogan on login page. Have you done those modification? If not, could you try to set a theme color of your choice and test LesPas login again?

I set the theme color to red. Still having the same issue though...I see the login screen color changed though. I noticed that I always have to click the login button twice to make it responsive if that's any indication of the issue

**Comment by scubajeff** [comment] 2022-04-26 05:33
I suspect that this's an issue with some graphic performance acceleration settings in your specific ROM. It's hard to debug this one, especially not with the device in my hand. If you really want to try out LesPas, I would suggest you taking the QR code scanning method for authentication.

**Comment by Sewdohe** [comment] 2022-04-26 16:54
By clicking login with token at the bottom? 

That gives me access forbidden invalid request error when clicking

**Comment by scubajeff** [comment] 2022-04-26 22:56
would you mind give me a screenshot?

**Comment by 80G5q1** [comment] 2022-05-09 18:59
I have the same problem with a Samsung S21plus running the original firmware with Android 12 and the  current version of Les Pas (2.5.8 from F.Droid)

I tried also using login with QR code (new app password). It seems, the login/password was not used corrextly. See attached screenshot
![Screenshot_20220509-205017_Les Pas_1](https://user-images.githubusercontent.com/64842926/167478569-62735c2c-4c02-4778-9a7c-43888704d016.jpg)

**Comment by scubajeff** [comment] 2022-05-11 03:11
@80G5q1 is it possible for you to get a screenshot in English?

**Comment by 80G5q1** [comment] 2022-05-11 05:51
Sure
![Screenshot_20220511-073849_Les Pas_small](https://user-images.githubusercontent.com/64842926/167777916-6ea2a352-4f39-4bea-bcfb-086bac6eb2eb.png)

**Comment by scubajeff** [comment] 2022-05-11 07:13
what happen if you click login button here?

**Comment by 80G5q1** [comment] 2022-05-11 07:47
The normal login screen but flickering. So it is not possible to type in name/password

**Comment by scubajeff** [comment] 2022-05-11 08:00
i understand that. what i'm asking is the other issue you mentioned, which is the qr code scanning didn't work neither. what happen after you scan the code?

**Comment by 80G5q1** [comment] 2022-05-11 08:35
The screen from the screen shot I sent. 

And Nextcloud did not recognize the login attempt.

**Comment by scubajeff** [comment] 2022-05-12 04:21
Les Pas shouldn't go to that screen after you scanned the QR code. Are you sure you were scanning the code from your server's security menu page?

**Comment by 80G5q1** [comment] 2022-05-12 04:56
Yes, I agree.  The QR code I scan is from the security page.

**Comment by 80G5q1** [comment] 2022-05-12 05:33
Regarding what happens after scanning the QR code I have to precise my answer:

DIrectly after scanning the QR code the first screen shows my nextcloud slogan flashing on my choosen colour. After one or two seconds it changes to the screenshot I sent.

**Comment by scubajeff** [comment] 2022-05-13 03:07
@80G5q1 Confirmed there is a bug prevents scanning from working. Fix will be released in version 2.5.10. 

Hope to push it out soon so that anybody who is facing this flickering situation can have a way out.

As for this issue itself, still have no clue what went wrong. Can't reproduce it at my side, it's not a crash so no log can be studied neither. Still suspect that it's related to specific implementation of webview and framework.

**Comment by scubajeff** [comment] 2022-05-13 14:58
@80G5q1 @Sewdohe would you like to test this debug build?
[LesPas-v2.5.9-debug.zip](https://github.com/scubajeff/lespas/files/8688802/LesPas-v2.5.9-debug.zip)

**Comment by 80G5q1** [comment] 2022-05-13 16:56
Top, it works for me!

**Comment by Sewdohe** [comment] 2022-05-13 20:52
> @80G5q1 @Sewdohe would you like to test this debug build? [LesPas-v2.5.9-debug.zip](https://github.com/scubajeff/lespas/files/8688802/LesPas-v2.5.9-debug.zip)

I'm still having the flickering issue :/

**Comment by scubajeff** [comment] 2022-05-14 01:50
@80G5q1 no flickering or still? if you have login, to test again, you just need to click the re-login menu in Setting screen.

**Comment by 80G5q1** [comment] 2022-05-14 07:21
Same 

> @80G5q1 no flickering or still? if you have login, to test again, you just need to click the re-login menu in Setting screen.

Login with scanning QR works without flickering, also the re-login in the settings. 

Login without scanning QR code is still not possible:  
- Flickering after using the "Log in" button
- "Error - Access Forbidden - Invalid request" screen message after pressing "Alternative log in using app token" multiple times. Single press usually did not work at all

**Comment by scubajeff** [comment] 2022-05-14 12:03
@80G5q1 you mean there is NO flickering in re-login screen?

**Comment by 80G5q1** [comment] 2022-05-14 12:14
re-login with scanning QR code works, re-login with "Log in" button flickers.

**Comment by scubajeff** [comment] 2022-05-15 01:40
@80G5q1 One more thing need to be clarified, during re-login, the first screen you see will be your server's login landing page, where you click the "Log in" button. You mentioned `Flickering after using the "Log in" button`, so you mean you didn't see flickers on this page?

**Comment by 80G5q1** [comment] 2022-05-15 07:22
Correct, the landing page with the "Log in" button does not flicker.

**Comment by scubajeff** [comment] 2022-05-15 11:36
@80G5q1 @SpeeterYT another try, could you please test this build?
[LesPas-v2.5.10-debug.zip](https://github.com/scubajeff/lespas/files/8694832/LesPas-v2.5.10-debug.zip)

**Comment by 80G5q1** [comment] 2022-05-15 13:43
> @80G5q1 @SpeeterYT another try, could you please test this build?
> [LesPas-v2.5.10-debug.zip](https://github.com/scubajeff/lespas/files/8694832/LesPas-v2.5.10-debug.zip)
> 
> 

- login and re-login works with scanning QR code
- login and re-login still not working. Landing page with "Log in" button ok, but flickering screen when pressed. 

Login with token also not possible. Most times nothing happens when pressing the button. Sometimes the expected landing page appears for a fraction of a second.


I also double checked to login to my cloud manually (Log in button and app token) with another app (Souvenirs via F-droid). This worked without problems.

Souvenirs also uses the possibility to use the accounts from the (installed) Nextcloud app, which is quite comfortable. This could be a new feature for Les Pas.

**Comment by scubajeff** [comment] 2022-05-15 14:29
@80G5q1 could you please post the output of this command:
```
 curl -X GET 'https://<your server's address>/ocs/v2.php/cloud/capabilities?format=json' -H "OCS-APIRequest: true"
```

**Comment by 80G5q1** [comment] 2022-05-15 14:37
I only replaced my server address: 

{"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK"},"data":{"version":{"major":23,"minor":0,"micro":4,"string":"23.0.4","edition":"","extendedSupport":false},"capabilities":{"bruteforce":{"delay":0},"theming":{"name":"Nextcloud","url":"https:\/\/nextcloud.com","slogan":"The answer is 42","color":"#575A7C","color-text":"#ffffff","color-element":"#575A7C","color-element-bright":"#575A7C","color-element-dark":"#575A7C","logo":"https:\/\/<my-server-address>\/core\/img\/logo\/logo.svg?v=10","background":"https:\/\/<my-server-address>\/index.php\/apps\/theming\/image\/background?v=10","background-plain":false,"background-default":false,"logoheader":"https:\/\/<my-server-address>\/core\/img\/logo\/logo.svg?v=10","favicon":"https:\/\/<my-server-address>\/core\/img\/logo\/logo.svg?v=10"}}}}}

**Comment by scubajeff** [comment] 2022-05-16 07:09
@80G5q1 that's seem pretty legit, is it possible to grab a logcat output when it's flickering?

**Comment by 80G5q1** [comment] 2022-05-16 10:39
> @80G5q1 that's seem pretty legit, is it possible to grab a logcat output when it's flickering?

Depends. I am not a SW developer. I guess I would have to connect the phone with a PC running some kind of Android development tool  - never really did this before.

**Comment by scubajeff** [comment] 2022-05-16 10:56
then forget it, it's much more troublesome than you think. ;)

**Comment by 80G5q1** [comment] 2022-05-16 19:33
I gave it a try. Maybe it is what you wanted. Should be from starting app until flickering by pressing "Log in" button

[LesPas-DEBUG.txt](https://github.com/scubajeff/lespas/files/8702883/LesPas-DEBUG.txt)

**Comment by scubajeff** [comment] 2022-05-17 00:36
So in fact, it's not that hard as what I thought it's. Welcome to the dev world!

I see a quite a few of this error in the log:
```
Refused to apply style from 'https://mydomain/apps/dicomviewer/css/sidebar.css?v=b0e8daa2-10' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```
I couldn't reproduce this error message in my environment. I'm not a web developer myself, I suspect that means android webview can't render the CSS style, which is very much related to page losing it's background.

Are you self hosting your Nextcloud on-premise or using a cloud service instance? Are you accessing your server using ip address or name? Is the name a public domain name? What webserver are you using?

**Comment by 80G5q1** [comment] 2022-05-17 05:38
Got it!
I have no idea why, but disabling the DICOM viewer app in NC solves the flickering problem. 

Btw: I am self hosting my own RPi4 NC instance with apache, accessible with a public domain name.

**Comment by scubajeff** [comment] 2022-05-17 07:44
How did you manage to pinpoint this app? I found out by search that this mimetype checking issues in Nextcloud has been on and off for many years, many Nextcloud apps hit this one.

**Comment by scubajeff** [comment] 2022-05-17 08:18
I see, it's in the link.

**Comment by scubajeff** [comment] 2022-05-18 02:34
I installed DICOM viewer app on my NC, still can't reproduce flickering on all my testing devices, didn't see that error message in logcat neither. This is really an edge case when ill-functioning NC app meets special webview implementation

**Comment by scubajeff** [comment] 2022-05-18 02:53
Here is another debug build, try to tell webview to ignore such css mime type error and continute to load the page. @80G5q1 @SpeeterYT @Sewdohe could you please have a try?
[LesPas-v2.5.10-debug.zip](https://github.com/scubajeff/lespas/files/8712945/LesPas-v2.5.10-debug.zip)

**Comment by 80G5q1** [comment] 2022-05-18 05:49
> Here is another debug build, try to tell webview to ignore such css mime type error and continute to load the page. @80G5q1 @SpeeterYT @Sewdohe could you please have a try?
> [LesPas-v2.5.10-debug.zip](https://github.com/scubajeff/lespas/files/8712945/LesPas-v2.5.10-debug.zip)
> 
> 

Still flickering when using Log In button. But I think my NC installation shouldn't be a reference. Initial installed as NC15 and continuesly upgraded since than incl. 2 server upgrades.

**Comment by nursoda** [comment] 2022-11-13 13:57
I see the same thing with the latest F-Droid build against my NC 25.0.1. It's impossible to enter anything, or even to press a button: [screencast.webm](https://user-images.githubusercontent.com/8425483/201525519-3e322fa2-5987-4313-b53c-2e6c1c06285e.webm)

**Comment by scubajeff** [comment] 2022-11-13 14:12
@nursoda It has been a long time since the last report of this issue. Is your NC instance accessible from internet? I need to give it a try from my side.

**Comment by palight** [comment] 2022-11-13 18:38
the  same for me. my instance is https://cloud.pesh.ch

**Comment by nursoda** [comment] 2022-11-13 21:25
Sure. Please self-register at
https://cloud.seyfarth.de/apps/registration/ Use a username matching /^[a-z-]+\.[a-z-]+$/ and a Password ≥14 characters. You may keep that account until you're finished testing. You may then self-delete it from the settings menu.

**Comment by scubajeff** [comment] 2022-11-14 08:04
@nursoda @palight Thank you very much for reporting. This long overdue bug fixed. I will release a new version asap.

**Closed** 2022-11-14 08:23 UTC

**Comment by Sewdohe** [comment] 2022-11-14 15:11
Awesome to hear! Been wanting to try this app for a long time! Been watching this issue
