### ISSUE TITLE
Album synchronization status and synchronization error status indicator needed.

### ISSUE THREAD

**Issue by raphaelporsche** [scubajeff/lespas#29] opened 2021-10-17 08:23 UTC
First let me thank you for all your great work, this app has the potential to become a Google Photos replacement!
One of the most needed features is a sync-status indicator in the main window since this is the main feature of les pas (are my photos securely saved in nextcloud?). Something like green=all photos synced, yellow=sync in progress (progress bar?), red=sync error, button to manually start a sync attempt.

Let me explain. I was happily using lespas together with my wife for several days. I had created the lespas-folder through nextclouds external storage functionality (just a folder on the local hdd) so we both had access to the same lespas folder and our albums where always in sync. This worked perfectly for some days until suddenly the sync stopped working (maybe we created some kind of conflict e.g. by modifying album settings on one phone etc.). We didn't notice this because there where no error messages (I couldn't find any logs!). There currently is no indicator wheter photos are synced or when there are any sync errors. We each kept on adding photos to albums till I noticed that none of the changes were in Nextcloud and we each had completly different albums. So I had to manually export all the photos from lespas for each album and then manually fused the albums which was quite the effort.

In my opinion knowing that the photos are safely synced to nextcloud (in case I loose the phone) would be one of the most important features.
Thanks again for your effort!

**Comment by raphaelporsche** [comment] 2021-10-17 11:27
I fully understand your point. Nevertheless I think even with a perfect robust sync system there will still be the need for a prominent visual indicator wheter sync has finished. Sync takes its time and is never instantaneous, users can be in the guest wlan instead of private wlan, nextcloud server can be down, vpn can be disconnected and users might want to know when they can turn on airplane mode safely. Such an visual sync indicator wouldn't need much visual room (e.g. a colored led or checkmark which you can tap on to show the sync log). What do you think?

**Comment by scubajeff** [comment] 2021-10-17 12:00
The sync is actually like a database log reply on the other side, where it stopped will always tell the cause of stopping.

**Comment by scubajeff** [comment] 2022-01-24 03:51
Not exactly a fix for this issue, but release 2.4.6 will now show camera roll backup status in Backup Camera Roll setting menu's summary.

**Closed** 2022-06-15 00:59 UTC
