### ISSUE TITLE
Do not jump to the first image if an image is deleted in the camera roll. #FeatureRequest

### ISSUE THREAD

**Issue by raphaelporsche** [scubajeff/lespas#57] opened 2022-05-06 08:32 UTC
If you delete an image in the camera roll, les pas jumps to the first image in the camera roll and you have to scroll down and search your last position. It would be better to jump to the image beneath the deleted image.

**Comment by scubajeff** [comment] 2022-05-06 09:30
which version are you using? Les Pas does exactly as what you suggest, jump to next one.

**Comment by raphaelporsche** [comment] 2022-05-06 09:36
I am able to recreate the behaving constantly (Les pas 2.5.8). Deleting a photo always jumps to the last image in camera roll media list.

**Comment by scubajeff** [comment] 2022-05-06 09:52
that's wierd. can't reproduce this though.

**Comment by raphaelporsche** [comment] 2022-05-06 12:53
Mi Note 10 Lite
MIUI 12.5.7 (stock)
Android 11

**Comment by scubajeff** [comment] 2022-05-06 14:10
MIUI again. Most edge cases reported so far are from MIUI. Guys in XiaoMi really like to alter the Android framework.

**Comment by raphaelporsche** [comment] 2022-05-07 19:06
I went so far to install Android Studio and boot up an emulator (Pixel 2 Device API 30):
![Screenshot_1651950231](https://user-images.githubusercontent.com/70773164/167268376-4b4056c0-ce45-43a1-ad3e-b650a34355ac.png)

Selecting and deleting image 2
![Screenshot_1651950253](https://user-images.githubusercontent.com/70773164/167268385-c5b78a47-300a-4d4b-a008-1562893f1ff1.png)

Image 5 or 3 should be selected, but 9 (the top most) is
![Screenshot_1651950258](https://user-images.githubusercontent.com/70773164/167268425-20ad6def-4030-4d09-ac09-3ea93f8f2b85.png)

**Comment by scubajeff** [comment] 2022-05-08 11:28
I'm about to release a new version which will revamp Camera Roll UX by adding the ability to manage archived camera roll images on server. This bug can not be reproduced on this branched codebase. So hold on for several days.

**Comment by scubajeff** [comment] 2022-05-30 16:05
fixed in release 2.5.10

**Closed** 2022-09-09 12:34 UTC
