### ISSUE TITLE
Les Pas maximizes bluetooth volume on app open

### ISSUE THREAD

**Issue by andreasmjg** [scubajeff/lespas#99] opened 2022-12-19 21:41 UTC
Hi,

Thanks for a great app. When I open Les Pas app, it maximizes the Bluetooth volume. This can be very disturbing. 

Les Pas 2.7.0 on FairPhone 4 using e/OS/ 1.6-s

Les Pas is the only app I use that does this. 

Thanks!
Andreas

**Comment by scubajeff** [comment] 2022-12-20 14:02
When app open or when video item starts playing?

**Comment by yuv** [comment] 2022-12-20 22:07
Same issue here on OnePlus Oxygen OS 11.0.9.1, and also when using regular phone speaker.

On tapping of Camera Roll the app "hijacks" the audio, everything else stops playing and the volume goes through the roof.  Probably it is when video item starts playing -- the first item in my Camera Roll at the time of testing was a video.  Can't the app behave like other apps, e.g. Telegram FOSS or Transistor (both from F-Droid) that can mix their sound together while leaving the volume unchanged?

I am not sure since when this bug is present.  I was using Les Pas without problems "before."  At some point it just shocked me (Bluetooth headset) and since then I am using Simple Gallery to avoid the pain, hoping for an update in F-Droid soon.

I confirm that Les Pas is the only app I use that does this.

Thanks!
Yuv

**Comment by scubajeff** [comment] 2022-12-20 23:19
Sorry folks, this bad behavior might due to Les Pas doesn't implement media session support yet. First priority now. See if I can get it done before X'mas

**Comment by scubajeff** [comment] 2022-12-24 03:51
Turns out the volume problem is due to the implementation of volume adjustment swipe gesture, fix is on the way to both app store now. For the audio focus hijacking problem, need more time to investigate, @yuv could you please give me the app name you are using for music playing?

**Comment by yuv** [comment] 2022-12-26 04:33
I typically have https://f-droid.org/en/packages/org.y20k.transistor/ when the audio focus is hijacked.

**Comment by scubajeff** [comment] 2022-12-27 06:15
The newer version of Lespas, which is now on Google Play and on the way to F-Droid, seems to be able to make this radio app fade-out when footage starts playing, but not able to resume playing radio stream when it quit.

**Comment by yuv** [comment] 2022-12-27 16:52
Tested. Behavior is better but still spurious:

- switching from single video play to Camera Roll still blasts the bluetooth volume to the roof
- I don't want Les Pas to stop/resume what is already playing.  I want it to behave like Simple Gallery Pro https://f-droid.org/en/packages/com.simplemobiletools.gallery.pro/:

1. no autostart 
2. on start, play simultaneously as the radio (or whatever else is already playing)

Reasoning:  no matter how "smart" an app is, it does not know what value I give to what I am listening/watching, nor to my attention at the time, and it is different in different contests.  Only I know how much attention I want to devote, divided or undivided, to the same things.  Any automatism, such as stealing the focus or auto-starting, is a hit or miss.  Frankly, most of the time it is a miss: If I want to devote full attention to the video on Les Pas, I will have deactivated everything else that I am letting eat my attention such as background music.  On the other hand, if I am just quickly browsing, e.g. to share on Telegram, the focus stealing, the auto-start, the stopping of other apps is a nuisance.  If I want to show a video to someone, I will first prepare, then call their attention, then start the movie.  Autostart before that is a time waster.

I really like much of what Les Pas does.  The GUI , The Camera Roll.  I am trying to tame my cell phone use to fit Les Pas.  Some of it (e.g. folder per event) was a natural for me in the pre-phone times:  over 20 years of images stored, some digitized, some originally digital, in yearly folders, and under each year subfolder per album.  The cell phone, at the moment, is just an automated backup using the (ugly) Nextcloud app, into the server using YYYY/MM folders that I am then *supposed* to sort later.  Does not really happen (no time) and I typically just move the photos that I take for documentation purpose (e.g. receipts for work) where they belong and leave the photo-album sorting for later.  I have not given Les Pas access to my NextCloud yet because it feels strange and uncontrollable.  I don't want the cell phone to delete stuff on the server because it is too easy to mis-tap or butt-dial.  I also want to manage cellular bandwidth usage manually because it is expensive and my (Canadian) cellular bandwidth provider plays nasty tricks with the competition (VOIP) forcing me to use a VPN if I want to receive my VOIP calls while on cellular.  AFAIK, no app can detect if a VPN is over cellular (no-sync) or over Wifi (do-sync).

Sorry for going off-topic in above paragraph.  Thanks for making and sharing Les Pas.

**Comment by scubajeff** [comment] 2022-12-27 20:02
I will try to provide a switch setting that control how the audio focus behaves in the future release.

Glad to know that this app fits in your workflow. There is a "Sync on WiFi only" switch in Setting menu, you can give it a try. Basically it will prevent the app from using cellar network for syncing photos.

**Comment by scubajeff** [comment] 2022-12-28 04:26
@yuv camera roll works as expected here with the new release, doesn't change the current volumn at it's start, can't reproduced the old bug

**Comment by yuv** [comment] 2023-01-03 17:49
Just tested.  It is reproducible.
1. pre-requisite: first item in the Camera Roll must be a picture, not a movie 
2. kill all apps / restart phone
3. start Transistor and play any radio station at reasonable volume over Bluetooth
4. start Les Pas
5. tap on the Camera Roll to see the picture full screen
4. swipe left until Les Pas displays a movie
5. swipe up to see the Camera Roll's thumbnails

Actual Results:
- at step 4, Les Pas takes exclusive possession of the audio focus and starts playing the movie at the expected volume
- at step 5, Les Pas hikes the Bluetooth volume to the max and audio playback continues to the end (or loops if Replay video automatically is on in Settings/View)

Expected result:
- at step 4, do not take exclusive possession and instead mix the movie's audio to the audio already playing, like Simple Gallery Pro (linked above) does
- at step 5, movie stops playing

**Comment by scubajeff** [comment] 2023-01-08 02:01
bug reproduced on my phone.

**Comment by scubajeff** [comment] 2023-01-08 09:55
Volume hiked is caused by swipe up gesture to reveal Camera Roll timeline list being wrongly treated as swiping up volume/screen brightness. The UI design is unpleasantly complicated in this screen

**Comment by scubajeff** [comment] 2023-01-08 13:43
Gesture conflict bug is fixed, will be included in next release

**Comment by yuv** [comment] 2023-01-12 00:02
merci! your commitment to this beautiful app is amazing, I look forward to test the update in F-Droid.

**Comment by scubajeff** [comment] 2023-01-12 00:29
Thanks @yuv . I'm having a long winter break with my kids now. Won't have access to my development machine till the end of the vacation. New release will be delayed.

**Comment by yuv** [comment] 2023-01-14 23:31
no hurry, @scubajeff -- skiing with the kid on this end as well and when I am back to work I will have much less time to pester you with bug reports ;-)

**Comment by scubajeff** [comment] 2023-02-09 03:05
fixed in new release 2.7.3

**Comment by yuv** [comment] 2023-02-17 17:49
confirm fixed! thanks. I wish I knew how to close this issue.

**Closed** 2023-02-18 00:27 UTC
